### ISSUE TITLE
SYCL Performance Regression in f527c4c

### ISSUE THREAD

**Issue by andreipoe** [UoB-HPC/bude-portability-benchmark#13]
Commit f527c4c decreases performance by more than 2X on Cascade Lake:

```
< 099e6ed
---
> f527c4c
12,13c12,13
< - Total time:     5603.552 ms
< - Average time:   700.444 ms
---
> - Total time:     12375.770 ms
> - Average time:   1546.971 ms
```

**Comment by tom91136** [comment]
Will fill in details after hearing back from Intel w.r.t `cl::sycl::native::sqrt`

**Comment by tom91136** [comment]
This has been resolved after upgrading to golden release of oneAPI
